--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6
-- Dumped by pg_dump version 16.6

-- Started on 2025-01-21 15:59:44 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16413)
-- Name: Taskreas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Taskreas" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Status" text NOT NULL,
    "AssignedUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Taskreas" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16412)
-- Name: Taskreas_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Taskreas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Taskreas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16405)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16404)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3607 (class 0 OID 16413)
-- Dependencies: 219
-- Data for Name: Taskreas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Taskreas" ("Id", "Title", "Description", "Status", "AssignedUserId", "CreatedAt", "UpdatedAt") FROM stdin;
1	Crear	Crear Uausrio	Pending	1	2023-11-23 13:30:00-05	2024-02-14 09:00:00-05
4	otro	otro	Pending	1	2023-11-23 13:30:00-05	2024-02-14 09:00:00-05
\.


--
-- TOC entry 3605 (class 0 OID 16405)
-- Dependencies: 217
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "PasswordHash", "Role") FROM stdin;
2	Jane Doe	janedoe@example.com	$2y$08$GAY7Ju3T6JbUmv82x22x8.xKLWnqEOiBLXTnD/OpqKvB6DTbnixQS	User
3	Administtrador Glen	admin@admin.com	$2a$11$MrDI3s.jv3Rapi3f368uyeB9pBcapri.58ZUaFAmV268lqbInTW8q	Admin
1	josh	user@user.com	$2y$10$0Lf.lf38wS6kBSAdDFSQpOtVxoLUg2JQaKYJC4X73J9.kLqA6nwc.	User
4	Lucrecia	lucre@lucre.com	$2a$11$RqyWeup/NROe32CxvwbNHO953aV6daWMLr7TeBBpMisErp0o1Ukqa	User
\.


--
-- TOC entry 3603 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250121021802_InitialCreate	9.0.1
\.


--
-- TOC entry 3613 (class 0 OID 0)
-- Dependencies: 218
-- Name: Taskreas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Taskreas_Id_seq"', 4, true);


--
-- TOC entry 3614 (class 0 OID 0)
-- Dependencies: 216
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 4, true);


--
-- TOC entry 3458 (class 2606 OID 16419)
-- Name: Taskreas PK_Taskreas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Taskreas"
    ADD CONSTRAINT "PK_Taskreas" PRIMARY KEY ("Id");


--
-- TOC entry 3455 (class 2606 OID 16411)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3453 (class 2606 OID 16403)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3456 (class 1259 OID 16425)
-- Name: IX_Taskreas_AssignedUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Taskreas_AssignedUserId" ON public."Taskreas" USING btree ("AssignedUserId");


--
-- TOC entry 3459 (class 2606 OID 16420)
-- Name: Taskreas FK_Taskreas_Users_AssignedUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Taskreas"
    ADD CONSTRAINT "FK_Taskreas_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


-- Completed on 2025-01-21 15:59:45 -05

--
-- PostgreSQL database dump complete
--

